@echo off
cd /d %~dp0..

set SIMULATOR_URL=ws://DROPLET_IP:3001
set GRID=7x2
set NUM_CANNONS=14
set GRID_COLUMNS=7
set BEYOND_HOST=127.0.0.1
set BEYOND_PORT=8000
set BEYOND_COLOR_MODE=rgb
set SHARD_START=0
set SHARD_END=13
set DEBUG_OSC=1

pnpm dev:receiver
